from textual.theme import Theme

darktheme = Theme(
    name="darktheme",
    primary="#6e86a6",
    secondary="#3e5d7a",
    accent="#FBB86C",
    foreground="#9DA2A8",
    background="#000000",
    success="#A3BE8C",
    warning="#EBCB8B",
    error="#BF616A",
    surface="#000000",
    panel="#1a2328",
    dark=True,
    variables={
        "block-cursor-text-style": "none",
        "input-selection-background": "#81a1c1 35%",
        "border": "#46ACB8",
        "scrollbar": "#000000 80%",
        "scrollbar-background": "#000000",
        "scrollbar-hover": "#000000 60%",
        "scrollbar-active": "#000000 60%",
        "button-foreground": "#9DA2A8",
        "button-color-foreground": "#9DA2A8",
        "button-focus-text-style": "none",
        "footer-background": "#000000",
        "footer-foreground": "#7A7E82",
        "footer-key-foreground": "#7A7E82",
        "primary-background-darken-2": "#000000",
        "secondary-background-darken-2": "#000000",
    },
)

lighttheme = Theme(
    name="lighttheme",
    primary="#6e86a6",
    secondary="#3e5d7a",
    accent="#FBB86C",
    foreground="#2f3438",
    background="#f6f7f9",
    success="#7FA06B",
    warning="#C9A861",
    error="#B85B63",
    surface="#f6f7f9",
    panel="#e7ecf1",
    dark=False,
    variables={
        "block-cursor-text-style": "none",
        "input-selection-background": "#6e86a6 25%",
        "border": "#3e5d7a",
        "scrollbar": "#c9d2da 80%",
        "scrollbar-background": "#f6f7f9",
        "scrollbar-hover": "#b4c0cb 80%",
        "scrollbar-active": "#b4c0cb 80%",
        "button-foreground": "#2f3438",
        "button-color-foreground": "#2f3438",
        "button-focus-text-style": "none",
        "footer-background": "#eef1f5",
        "footer-foreground": "#4a5157",
        "footer-key-foreground": "#4a5157",
        "primary-background-darken-2": "#e7ecf1",
        "secondary-background-darken-2": "#e7ecf1",
    },
)
